# Generated by Django 3.2 on 2021-05-13 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('serial_num', models.CharField(max_length=150)),
                ('added_to_clinic', models.DateTimeField()),
                ('removed_from_clinic', models.DateTimeField(null=True)),
                ('from_zone', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('problem', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField()),
                ('serial_num', models.CharField(max_length=150)),
                ('valid_after', models.DateTimeField()),
                ('valid_before', models.DateTimeField(null=True)),
            ],
        ),
    ]
