# Generated by Django 3.2.3 on 2021-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_clinicitem_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default='default name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicitem',
            name='tag_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='tag_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_id',
            field=models.CharField(max_length=50),
        ),
    ]
